### ISSUE TITLE
[Help] Config and docker-compose

### ISSUE THREAD

**Issue by otroboe** [nestjs/typeorm#11]
Hey guys !

I'm using docker-compose for my mysql server, but I'm quite annoyed by having connection configuration in two different places:
`docker-compose.yml`
`ormconfig.json`

Would you have some ideas how to keep the connection in only one place ?

**Comment by otroboe** [comment]
I'm closing it, it's not related to Nest, but TypeORM :-)

**Comment by jcloutz** [comment]
@otroboe Take a look at using a .env file for config. It has some limitations with typeorm if you want to use more than one database but it should get the job done in most cases

[Docker Compose Environment Vars](https://docs.docker.com/compose/environment-variables/) & [Typeorm](http://typeorm.io/#/using-ormconfig/loading-from-ormconfigenv-or-from-environment-variables)

If you couple with something like [Direnv](https://direnv.net/) to parse the .env file when you enter the directory it should work out pretty good.

```
# .env
HOST=localhost
PORT=8000
NODE_ENV=development
LOG_LEVEL=debug

TYPEORM_CONNECTION=postgres
TYPEORM_HOST=localhost
TYPEORM_USERNAME=postgres
TYPEORM_PASSWORD=postgres
TYPEORM_DATABASE=project_database
TYPEORM_PORT=5432
TYPEORM_SYNCHRONIZE=false
TYPEORM_DROP_SCHEMA=false
TYPEORM_LOGGING=all
TYPEORM_ENTITIES=src/common/entity/**/*.ts
TYPEORM_MIGRATIONS=src/database/migrations/**/*.ts
TYPEORM_SUBSCRIBERS=src/database/subscribers/**/*.ts
```

```
# .envrc used for direnv to modify shell when entering directory

# add {project_dir}/bin to path for helpers
export PATH=$(PWD)/bin:$PATH

# parse .env file when entering project dir
export $(egrep -v '^#' .env | xargs)
```

```yml
version: '3.1'

services:
  pgsql:
    image: postgres:9
    ports:
      - ${TYPEORM_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    volumes:
      - pg_data:/var/lib/postgres/data

volumes:
  pg_data:
```

**Comment by otroboe** [comment]
Thank you ! I'll test your solution as soon as I can.

**Comment by jcloutz** [comment]
@otroboe another cool thing you can do with direnv is create shell scripts for a specific project and modify the path for the current working directory.

This works like a charm with typeorm, i got annoyed having to invoke ts-node everytime i wanted to create or run migrations.

```bash
#!/bin/bash
#/path/to/program/bin/typeorm

./node_modules/.bin/ts-node ./node_modules/.bin/typeorm $1 $2 $3 $4 $5
```

**Comment by joshuamanns** [comment]
@jcloutz you can also load the .env file within docker-compose using `env_file` instead of enumerating each value:
```
version: '3.1'

services:
  pgsql:
    image: postgres:9
    ports:
      - ${TYPEORM_PORT}:5432
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgres/data

volumes:
  pg_data:
```
