### ISSUE TITLE
TypeOrmCoreModule module initialization took to much time

### ISSUE THREAD

**Issue by RidgeA** [nestjs/typeorm#94]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
Application initialization with TypeORMModule takes to much time, IMHO
I have an application that communicates only with one DB (PostgreSQL) that runs locally (inside Docker container)
The application initialization took more than 3 seconds:
```
[Nest] 15999   - 04/08/2019, 2:36 PM   [NestFactory] Starting Nest application...
[Nest] 15999   - 04/08/2019, 2:36 PM   [InstanceLoader] AppModule dependencies initialized +12ms
[Nest] 15999   - 04/08/2019, 2:36 PM   [InstanceLoader] CoreModule dependencies initialized +1ms
[Nest] 15999   - 04/08/2019, 2:36 PM   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 15999   - 04/08/2019, 2:36 PM   [InstanceLoader] HealthModule dependencies initialized +17ms
[Nest] 15999   - 04/08/2019, 2:36 PM   [InstanceLoader] TypeOrmCoreModule dependencies initialized +3115ms
...
```

Configs:
```
  postgres:
    type: postgres
    host: localhost
    port: 5432
    username: postgres
    password: root
    database: db
    entities:
      - "**/**/*.entity.{ts,js}"
    synchronize: false
    logging: true
    migrationsRun: false
```

## Environment

<pre><code>
$ nest -V
6.0.0
$ node -v
v11.13.0
$ npm list -depth 0 | grep -iE "TypeORM|pg"
├── @nestjs/typeorm@6.0.0
├── pg@7.9.0
├── typeorm@0.2.16
$ uname -sr
Linux 5.0.5-200.fc29.x86_64 # Fedora 29
</code></pre>
